### PR TITLE
Added more math functions

### PR DESCRIPTION
**Pull request by Zueuk**
Now with LLVM code generation.

### CODE REVIEW

**Review by mvhooren — CHANGES_REQUESTED** [review]
Looks good to me, except that I would like the LLVM code generation to also be implemented before merging this pull request. LLVM has some built in intrinsics for math functions but I had a little look and most of what you added does not have a LLVM built-in intrinsic. Probably the easiest way to implement your math functions is to add the relevant switch cases in LLVMCodeGenerator.cpp and then generate a call to the c++ versions of those math functions. For example:

```c++
case CatBuiltInFunctionType::Asin
{
    llvm::Value* x = helper->convertType(generate(arguments->getArgument(0), context), LLVMTypes::floatType, context);
    return helper->createCall(context, &std::asinf, {x}, "asin");
}```

**Comment by Zueuk** [comment]
Oh nice, I was not sure how to do this properly. Do we need `helper->convertType()` though? That argument type was probably converted to float a few times already.

**Comment by Zueuk** [comment]
One thing I am quite confused about is this stuff in LLVMCodeGenerator::LLVMCodeGenerator():
```
intrinsicSymbols[executionSession->intern("sinf")] = llvm::JITEvaluatedSymbol(reinterpret_cast<llvm::JITTargetAddress>(&sinf), functionFlags);
intrinsicSymbols[executionSession->intern("_sin")] = llvm::JITEvaluatedSymbol(reinterpret_cast<llvm::JITTargetAddress>(&sinl), functionFlags);
```
How are these "intrinsics", if you just add the usual library functions here? (and why add long double versions?)

I was kind of expecting LLVM to use some inlined sin/cos code that it knows how to optimize, otherwise it just does not make sense.

**Comment by mvhooren** [comment]
> One thing I am quite confused about is this stuff in LLVMCodeGenerator::LLVMCodeGenerator():
> 
> ```
> intrinsicSymbols[executionSession->intern("sinf")] = llvm::JITEvaluatedSymbol(reinterpret_cast<llvm::JITTargetAddress>(&sinf), functionFlags);
> intrinsicSymbols[executionSession->intern("_sin")] = llvm::JITEvaluatedSymbol(reinterpret_cast<llvm::JITTargetAddress>(&sinl), functionFlags);
> ```
> 
> How are these "intrinsics", if you just add the usual library functions here? (and why add long double versions?)
> 
> I was kind of expected LLVM to use some inlined sin/cos code that it knows how to optimize, otherwise it just does not make sense.

I think LLVM will first attempt to find some machine instruction for implementing the intrinsics and only if it cannot generate an instruction will it call the intrinsic symbol we have provided. Since we do not know in advance if the jit compiler will find an instruction, we always have to provide a intrinsic symbol as a fallback.

**Comment by Zueuk** [comment]
Well, I provided a fake sin() that returns wrong values, and it seems to be called all the time...

**Comment by mvhooren** [comment]
> Well, I provided a fake sin() that returns wrong values, and it seems to be called all the time...

Its probably true that currently the llvm intrinsics will always call the library functions that are provided. In order for LLVM to generate instructions instead of library calls, some fast/unsafe-math flag needs to be enabled. Probably not somethin that should be enabled by default. This is what I found in LLVM's TargetOptions.h:

```c++
    /// UnsafeFPMath - This flag is enabled when the
    /// -enable-unsafe-fp-math flag is specified on the command line.  When
    /// this flag is off (the default), the code generator is not allowed to
    /// produce results that are "less precise" than IEEE allows.  This includes
    /// use of X86 instructions like FSIN and FCOS instead of libcalls.

**Pull request merged**
